[package]
name = "llamaex"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "llamaex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.28.0"
llm = "0.1.1"
rand = "0.8.5"

#[profile.dev.package.ggml-sys]
#opt-level = 3
